typography_spectrum: 0.5946009068284184
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0
  lightness: 0.375
  saturation: 1
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Max Nylin
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Things.
purpose: []
